name: Android Release

# 1
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop
    # Sequence of patterns matched against refs/tags
    tags:
      - v*
      - v1.*
      - 'v*.*.*'

  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
      # 10
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # 12
      - name: Get Flutter version
        run: flutter --version
      # 12
      # - name: Get dependencies
      #   run: flutter pub get

      # # Runs a set of commands using the runners shell
      # - name: Start release build
      #   run: flutter build apk

      - name: List build dir
        run: ls ./build/app/outputs/apk/release/

      # - uses: actions/checkout@v3
      # - name: Get version.txt
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: gitversion

      # - name: Create new file without newline char from version.txt
      #   run: tr -d '\n' < version.txt > version1.txt

      # - name: Read version
      #   id: version
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: version1.txt

      # - name: Update version in YAML
      #   run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml

      - name: 🛎️ Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v2.2
          artifacts: './app-release.apk'
          draft: true

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: ./build/app/outputs/apk/release/

      - name: Archive release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist with release
          path: ./app-release.apk
