name: Android Release

# 1
on:
  # 2
  push:
    branches: ['develop']
  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
      # 10
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # 12
      - name: Get Flutter version
        run: flutter --version
      # 12
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk
      - name: List build dir
        run: ls ./build/app/outputs/apk/release/app-release.apk
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get App version
        id: lookupSdkVersion
        uses: devorbitus/yq-action-output@v1.1
        with:
          cmd: yq eval 'version' 'pubspec.yaml'
      - name: Print app version
        run : echo steps.lookupSdkVersion.outputs.result  ${{ steps.lookupSdkVersion.outputs.result }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/app/outputs/apk/release/app-release.apk
      - name: Archive release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist with release
          path: ./build/app/outputs/apk/release/
